#!/usr/bin/env bash
# foundry-companion Weekly Tidy Script
# Runs ESLint auto-fix, Prettier, TypeScript check, and opens a PR
#
# Usage: bash lib/ci-scripts/weekly-tidy.sh
# Designed for cron on Monday 9am

set -euo pipefail

PROJECT_DIR="/home/talos/foundry-companion"
BRANCH="tidy/$(date +%Y-%m-%d)"
cd "$PROJECT_DIR"

echo "=== Weekly Tidy: $(date) ==="

# 1. Create a branch off the latest main
git checkout main 2>/dev/null || git checkout master 2>/dev/null
git pull origin 2>/dev/null || true
if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  git branch -D "$BRANCH"
fi
git checkout -b "$BRANCH"

# 2. Run ESLint auto-fix
echo "--- ESLint auto-fix ---"
npx eslint --fix . --max-warnings=200 2>&1 || true

# 3. Prettier
echo "--- Prettier ---"
npx prettier --write . 2>&1 || true

# 4. TypeScript check — report errors but don't block
echo "--- TypeScript check ---"
npx tsc --noEmit 2>&1 | tail -50 || true

# 5. Check if there are any changes
if git diff --stat --quiet; then
  echo "No changes found. Nothing to PR."
  exit 0
fi

# 6. Commit and push
echo "--- Committing changes ---"
git add -A
git commit -m "chore: weekly tidy $(date +%Y-%m-%d)

Auto-fixes from ESLint, Prettier, and dependency housekeeping.
Generated by the weekly-tidy cron job." || true

git push origin "$BRANCH" 2>&1 || true

# 7. Open a PR using gh CLI
if command -v gh &>/dev/null && gh auth status &>/dev/null 2>&1; then
  echo "--- Opening PR ---"
  gh pr create \
    --base main \
    --head "$BRANCH" \
    --title "chore: weekly tidy $(date +%Y-%m-%d)" \
    --body "Automated weekly code quality tidy-up.

- ESLint auto-fixes
- Prettier formatting
- TypeScript check (reported, not blocking)
- Any other housekeeping

Review and merge at your convenience." 2>&1 || echo "gh pr create failed — check auth"
else
  echo "gh CLI not authenticated. Branch $BRANCH pushed but no PR created."
fi

echo "=== Weekly Tidy complete: $(date) ==="
